# Generated by Django 2.2.1 on 2019-05-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_request_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='requests',
        ),
    ]
