# Generated by Django 2.2.1 on 2019-05-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0003_lesson_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
        migrations.AlterModelTable(
            name='like',
            table='likes_on_lessons',
        ),
    ]
