# Generated by Django 2.2.1 on 2019-05-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0004_auto_20190516_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
