# Generated by Django 2.2.1 on 2019-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20190522_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
